### ISSUE TITLE
Dynamic Downloads not routing

### ISSUE THREAD

**Issue by axbrev** [gyng/save-in#103]
Not sure if I am missing something here but tried a simple routing rule using the guide and it still keeps going to the "downloads" folder.  Any idea why - is there anything further I need to do after installing the extension?  I need to do more complex rules but tried the basic example below and still couldn't get to work.

fileext: zip
into: zips/:unixdate:.:fileext:

**Comment by gyng** [comment]
Are you using the download via the context menu option? The extension only routes if the download is triggered that way.

**Comment by axbrev** [comment]
Ah ok that explains it, dont think I noticed that it worked that way in any of the documentation.  

Are there any plans to have this work without the context menu?  I think this extension would be even more useful with this ability.  I currently use an extension "Downloads Router" for this but I think your routing logic is much more advanced - eg. that extension only looks at the host in the url not a full url.  But thats just a minor example, your extension can do so much more.

**Comment by gyng** [comment]
It might be possible; it's something I can consider. Will need some more investigation though.

**Comment by axbrev** [comment]
Thank you!  Happy to test if needed.  Would be amazing.
