### ISSUE TITLE
[solved] conflict filename and page title

### ISSUE THREAD

**Issue by xxyyzz2050** [gyng/save-in#109]
this extension make confictions with other extensions such as : Save page WE
when this ext. enabled and trying to save a page using save page WE, it gives wrong filename and page title, it gives the last filename and extension that downloaded via Save in, for example it save an image file instead of the intended html page

note: I don't want to use save in to save full page archive (html)

**update**
fixed in version 3.4.1 [commit #00ca8...](https://github.com/gyng/save-in/commit/00ca8b8de6b7bb0fffd3fee1f9d004a10c2b3c03)

**Comment by gyng** [comment]
Is this on Chrome, or on Firefox?

**Comment by gyng** [comment]
@xxyyzz2050 can you try again in 3.4.1? It might be fixed.

**Comment by pablo712** [comment]
Hello, after last update, it's not working for me.

This is what I usually use it for:
// Add ISO date to filenames
filename: .*
into: :pagetitle:.zip	

now it gives error with any rule I use it

**Comment by xxyyzz2050** [comment]
@gyng fixed, thank you <3

**Comment by gyng** [comment]
@pablo712 I don't know what could have broken it, if possible can you try resetting to defaults?

**Comment by pablo712** [comment]
> @pablo712 I don't know what could have broken it, if possible can you try resetting to defaults?

I already tried, but it is not working for me, neither in firefox or chrome. Does it work for you?

**Comment by gyng** [comment]
@pablo712 yes, your rule seem to work for me. Does anyone else have this problem?

**Comment by pablo712** [comment]
@gyng all good now. It looks like there was a bug with the link. thanks a lot
