### ISSUE TITLE
Click to Save doesn't work

### ISSUE THREAD

**Issue by MindlessCirno** [gyng/save-in#116]
Is it just for me or "Click to Save" feature stopped working with new firefox version (68.0)? I.e., nothing happens after execution of shortcut

**Comment by gyng** [comment]
Needs investigation.

**Comment by gyng** [comment]
@pescadito @MindlessCirno do you have additional details? It seems to work for me still on 69.

**Comment by MindlessCirno** [comment]
I tried it now the new profile and it works only with modifier + "left click", not "right click" or "middle click".
Win 8.1 x64, firefox 69.0.1 (64-bit)

**Comment by gyng** [comment]
This should be fixed in 3.5.1.

**Comment by MindlessCirno** [comment]
Yes, it works now. Thanks a lot!
