### ISSUE TITLE
[Feature Request] Separators in submenus

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#117]
I might be missing something obvious, but I couldn't figure out how to have separators in submenus, i.e. at `Save In` > `something` > `this level` or further nested? I tried `>---`.

**Comment by gyng** [comment]
This should be fixed in 3.5.1.

**Comment by FatOrangutan** [comment]
Little issue I noticed: separators in submenus seem to consume number key shortcuts. So `Save In` > `separators don't consume shortcuts at this level` > `but they consume it at this level`.
