### ISSUE TITLE
[Request] Menu name to filename

### ISSUE THREAD

**Issue by color-space** [gyng/save-in#138]
I want to use the comment/alias of the menu that i saved an element under to be integrated into its filename.

so for example:
```
_Games
>_Games/Baseball // (alias: Baseball)
>>_Games/Baseball //dunks (alias: Dunks)
>>_Games/Baseball //historical (alias: Historical)

```

and something like

```
comment: .
filename: .
capture: comment
into:  :$1:-:filename:
```

So that i can have all files in the same folder and avoid duplicates but still categorize them through name. 
And possibly there should also be addition mode.
something like 

```
...
into:  :$1:-:filename:
prepend:  :$1:-
```

So the first time you save, it will be` category-filename` => `dunks-michaeljordon.jpg` , second time you save it will just update the name to `category-category-filename` => `historical-dunks-michaeljordon.jpg` and so on. maybe check on right click of media if it already exists and show categories as tags in the context menu => `tags of this file: dunks, historical`?

maybe a whole tag system would be better

**Comment by gyng** [comment]
I believe this can be somewhat done with the `comment` matcher right now. Try this:

```
>Games
>>Baseball // (alias: dunks) dunks
```

```
comment: dunks
into: ./dunks/filename
```
