### ISSUE TITLE
Keyboard Shortcut feature/suggestion

### ISSUE THREAD

**Issue by Solid-Ice8** [gyng/save-in#139]
Please add keyboard shortcut for this add-on (_Manage Shortcuts_ doesn't display it).

As I know, we can use numbers 1-9 (haven't tried 0) to save to respective folders and it works perfectly.

edit:
I have done some exploring. Apparently the letter "e" is the keyboard shortcut for this add-on and I have tested this shortcut on my other profiles that do not have this add-on.

Simply right-click anywhere and press "e" and save-in context menu will open the menu.

**Comment by gyng** [comment]
Yes, this is a "hidden" feature, depending on your OS. If you want more advanced integration, you can check out FoxyGestures integration at https://github.com/gyng/save-in/wiki/Use-with-Foxy-Gestures.

**Comment by Solid-Ice8** [comment]
Will do, thanks.
