### ISSUE TITLE
Does not work for youtube video

### ISSUE THREAD

**Issue by def00111** [gyng/save-in#14]
20:08:50.408  is not a valid URL. 1 download.js:48
	replaceSpecialDirs moz-extension://422fc9c2-6501-435d-b927-b1183e0c847a/src/download.js:48:49
	<anonym> moz-extension://422fc9c2-6501-435d-b927-b1183e0c847a/src/index.js:118:24
	apply self-hosted:4213:5
	applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
	applySafe resource://gre/modules/ExtensionCommon.jsm:272:14
	sync resource://gre/modules/ExtensionCommon.jsm:1570:18
	listener/< chrome://browser/content/ext-c-menus.js:168:41
	withHandlingUserInput resource://gre/modules/ExtensionUtils.jsm:125:12
	listener chrome://browser/content/ext-c-menus.js:167:13
	apply self-hosted:4213:5
	applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
	fire resource://gre/modules/ExtensionChild.jsm:831:28
	receiveMessage resource://gre/modules/ExtensionChild.jsm:834:38
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:865:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:864:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:939:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:936:24
	_handleMessage self-hosted:954:17
	receiveMessage/< resource://gre/modules/MessageChannel.jsm:209:9
	forEach self-hosted:273:13
	receiveMessage resource://gre/modules/MessageChannel.jsm:202:5

**Comment by gyng** [comment]
I don't think it's possible to download directly from the DASH YouTube player. They do weird things around the video source.

You can try using another addon that generates direct links for download and then save those links instead. [The one I tried](https://addons.mozilla.org/en-US/firefox/addon/easy-youtube-video-download/) worked with this, but I don't use it personally.

**Comment by gyng** [comment]
I won't have the energy or time to keep up-to-date with the major video sites. The workaround above should work.
