### ISSUE TITLE
Getting Save in to save samples in iCloud

### ISSUE THREAD

**Issue by Mrswalbard** [gyng/save-in#140]
Hi, I'm writing because i wonder if you can help me set up save in so that i can store samples in my samples folder directly, immensely improving my music workflow! Also it would be neat if it could be in iCloud so it doesn't take up much storage on my computer! :D Cheers // Andreas Löwing

**Comment by gyng** [comment]
I'm not familiar with how iCloud works, but you can try

* syncing the folder with iCloud (https://support.apple.com/en-us/HT206985), or
* creating a symlink to the shared iCloud directory,
