### ISSUE TITLE
Comments option not working.

### ISSUE THREAD

**Issue by Dreykku** [gyng/save-in#141]
Hi,

It is said we can add comment after the "//" but it doesn't seem to be working.
Even the demo comment doesn't work (>submenu/subdir2 // comments)
When you say "comment", you mean the comments within the descriptions in the file propriety or or that something else? 
I'm not sure what it's supposed to mean (or do), but if it's that, even though it may not be an important feature, i can't make it work. 

Thank you.

**Comment by gyng** [comment]
Hello, comments are just for the directory description. WebExtensions in general cannot modify downloaded files.
