### ISSUE TITLE
~ Character stopped process on Vivaldi

### ISSUE THREAD

**Issue by Darkwolflair** [gyng/save-in#151]
Hello,

First, thanks a lot for that awesome extension.

I noticed an issue on Vivaldi (it works on Firefox) : 

Il love saving images with pagetitle as prefix.

But when a pagetitle has the "~" character on it, it prevents the save of the image : 

To make a test with Chrome or Vivaldi : 

https://www.artstation.com/artwork/rAOx6G

Thanks a lot in advance.

Kind Regards.

**Comment by gyng** [comment]
Sorry, but Vivaldi is not a supported browser, I simply don't have the resources for maintenance.

**Comment by Darkwolflair** [comment]
Hello, 

thanks for feedback. I just try with latest version of Chrome, and I still have the same issue (Vivaldi base on Chrome, that's must be the explanation).

Kind regards.
