### ISSUE TITLE
Twitter images save without filename

### ISSUE THREAD

**Issue by tombones** [gyng/save-in#157]
When saving either from the main twitter feed or from the image itself (opened via "open image in new tab" extension), Save In just saves the image without a filename. If you rename the file with an image extension like .png it can be viewed, but obviously this is a problem if you're saving a lot of images from twitter.

for example, try saving the images from either of these links.

https://twitter.com/Catlawn/status/1334322472280338433
https://pbs.twimg.com/media/EoR2-7eWEAAkDVa?format=jpg&name=orig

I assume this is happening because the url itself shows parameters instead of a normal filename, because jack dorsey is a monster

anyway this extension rules and i couldn't use firefox without it, thanks for keeping it going!

**Comment by gyng** [comment]
Does https://github.com/gyng/save-in/wiki/Filename-rewrite#twitter-media-images help?

**Comment by tombones** [comment]
That seems to have fixed it! Thank you so much
