### ISSUE TITLE
Cannot save to hidden folder

### ISSUE THREAD

**Issue by sammoth** [gyng/save-in#16]
This is related to issue #7

I am trying to save to a hidden folder in my download directory, eg. `~/downloads/.hidden/`

It was working in FF 57 but has stopped working with 58. I was using `.hidden/` in the settings but the dot is stripped, resulting in files being saved to `~/downloads/hidden/`. If I use `..hidden/` or `./.hidden/` in the settings, when saving files I get the same error in the debug console as in #7:

`.hidden .hidden/8075205dly1fl76vtbio8j21kw2dbb2f.jpg  download.js:169:5
Error: filename must not contain illegal characters`

**Comment by gyng** [comment]
Thanks for the report. Maybe a change in ff58? Have to investigate further.

**Comment by gyng** [comment]
Upon further investigation: Firefox made a change as to what it considers a valid download path when the downloads API is used.

The caller, from the downloads API: https://dxr.mozilla.org/mozilla-central/rev/d4753dc14b2ab9c42123b6d60a68106df40f45cd/toolkit/components/extensions/ext-downloads.js#434

```
if (path.components.some(component => component != DownloadPaths.sanitize(component))) {
  return Promise.reject({message: "filename must not contain illegal characters"});
}
```

calls `DownloadPaths.sanitize` and checks the result for equality

https://dxr.mozilla.org/mozilla-central/rev/d4753dc14b2ab9c42123b6d60a68106df40f45cd/toolkit/components/jsdownloads/src/DownloadPaths.jsm#70

>`Leading and trailing dots and whitespace are removed on all platforms.`

I don't have the time right now to create a minimal example to file a bug report upstream. For now directories beginning with a dot (even if nested) cannot be used.

**Comment by gyng** [comment]
Curiously, I tried this again with `./.hidden` and on OS X, it seems to work on OS X. Is the bug still happening for you?

**Comment by sammoth** [comment]
Still seems to be happening for me on the latest 58 and 59 (on Linux)

**Comment by gyng** [comment]
It only happens on >= 58. I've filed a bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1420005

**Comment by gyng** [comment]
This is a WONTFIX, see the Bugzilla report for details. I've added a line in options that says directories with leading dots don't work. In the future validation on paths have to be done.

For the record, it also doesn't seem to work on Chrome.

**Comment by sammoth** [comment]
Thank you for investigating and for the extension!
