### ISSUE TITLE
Feature request: add ability to save current page as a link

### ISSUE THREAD

**Issue by CottonEaster** [gyng/save-in#17]
The non-webExtension addOn [SaveLink](https://addons.mozilla.org/en-US/firefox/addon/savelink/) allows one to save the current page as a link. That function is very convenient. I'd love to see it in your excellent addOn.

**Comment by gyng** [comment]
This will have to be a separate extension, I think. Will have to write shortcut files manually.

**Comment by gyng** [comment]
Landed in 1.6.0. Please reopen if it doesn't seem to work as intended.
