### ISSUE TITLE
Symlink tweak to save outside Downloads folder doesn't work in Firefox Flatpak version

### ISSUE THREAD

**Issue by LukasThyWalls** [gyng/save-in#185]
Hello.

### Disclaimer:

I think this is an issue with Flatpak itself and not with Firefox or Save-In addon, but maybe I'm doing something wrong, although I don't think is the case, and I want to gather all information I can to put it in the Flatpak issue tracker and confirm this is not working for other people too, or maybe this is something known that is discussed somewhere, but i didn't found yet.

### Summary: 

Simply the known symlink tweak to save outside the Downloads folder with Save-In doesn't work in the Flatpak version. I had it working with the Snap version in the same computer, and for sure it works in the Windows version in other one.

### Explanation:

I have a hidden folder (using .hidden file) in Downloads called "Firefox_WebEx", with inside two symlinks **Desktop** and **USBDisk**. **Desktop** goes to _/home/<myuser>/Desktop/_ and **Disk** goes to _/media/<myuser>/USBDisk/Files_ which is a USB Disk, with some folders inside (one of them "Downloads"), making the symlink available only when is plugged in. Also i made a folder called "Test" only for testing this.

Both symlinks works in the file explorer, Dolphin (Obviously the USB Disk one works when the USB Disk is plugged and not when it isn't) so the symlinks are right configured working.

In Save-In, i have these paths configured:

```
Firefox_WebEx/USBDisk/Files/Downloads // symlink 
Firefox_WebEx/Desktop // symlink
. // (alias: Downloads)
---
Firefox_WebEx // parent folder
Firefox_WebEx/Test // folder
```

Like I said, with the Firefox Snap version, I had no issues with this configuration. However, using the Firefox Flatpak version both, symlinks doesn't work, but everything else does.

* With Desktop, it shows an error of FILE_FAILED, an opens a save dialog with path _/run/user/1000/doc/3be22eff/_, what seems the temp folder used by the flatpak version at that moment. It appears as Failed in Firefox Downloads Manager.
* With USBDisk (obviously with the USB Disk plugged), there is no error or any indication of what it does (i have notifications for successful downloads too) but it doesn't save anything. Also it doesn't appear as Failed in Firefox Downloads Manager.
* Every other path work as intended, so only are failing the symlinks.

Also I tested to "Save as" with Firefox using the save path throw the symlinks, and they work.

### Questions:

* Is it happening to other people or only me?
* Is there a way to show a more specific error or response to see what's the issue? I looked it to the developer console, but I didn't see any error or anything. Something to add additional information to use to report to flatpak or firefox issue trackers. (i saw the "Enable debug logging" option but i don't know where to find the log)

Thanks!!

**Comment by gyng** [comment]
>Is there a way to show a more specific error or response to see what's the issue? I looked it to the developer console, but I didn't see any error or anything

You'll have to check the extension's developer console ([instructions](https://github.com/gyng/save-in/wiki/Getting-detailed-error-logs#firefox)).

>`FILE_FAILED`

Unfortunately FF doesn't have good error messages for failed downloads. I don't know if you'll get better error logs from the developer console.

I haven't tried it yet, but a bindmount (`mount --bind`) could help.

**Comment by Martii** [comment]
FWIIW I've also seen this issue in the snap package.

**Comment by LukasThyWalls** [comment]
Hello.

After posting in the Flatpak issue tracker, the issue is related to the permission isolation of the Flatpak package.
You need to specify in the Firefox Flatpak configuration (I used Flatseal to make it easy) the paths you need to access outside the Downloads folder, including the ones you go throw the symlinks (You can also allow to access to all filesystem, but doesn't seem the best idea). Is explained here https://github.com/flatpak/flatpak/issues/4994#issuecomment-1185796543 .

It's funny, because the symlinks workaround is made to "trick" Firefox, but in this case you need to "reveal" the trick to the Flatpak engine to keep tricking Firefox.
I don't know if some flexibility in the future with the webextensions API downloads folder could help to improve this (Firefox notifying Flatpak what folders need to reach), but at the moment doesn't seem that can be done anything more than this.

Maybe can be detailed this detail with the flatpak package where are explained the symlink workaround, only to be warned in that case.

I will keep open the issue only to make @gyng aware of this, but can be closed now.

**Comment by gyng** [comment]
Glad you figured this out!
