### ISSUE TITLE
Feature request: Allow saving selected text with url

### ISSUE THREAD

**Issue by yoyoma2** [gyng/save-in#19]
The savetexttofile addon no longer works in firefox 57.  Allowing the user to select **text** and save/append it along with the page url would complete this addon's existing ability to save images/video/audio.

**Comment by gyng** [comment]
I don't see anyway of doing this through the downloads API. I'm open to implementing this though.

**Comment by gyng** [comment]
1.5 has a feature to save selected text. It's disabled by default, and you need to put a rewrite rule to rename the files, but it's something, at least.

The filename rewrite rule for Firefox:

```
.{8}-.{4}-.{4}-.{12}
:pageurl:.txt
```

and Chrome:

```
.{8}-.{4}-.{4}-.{12}.txt
:pageurl:.txt
```

Please reopen if it doesn't work as expected.

**Comment by gyng** [comment]
The default filename is now the page title instead of the blob ID.

Instead, use

```
.*.selection.txt
:pageurl:.txt
```
