### ISSUE TITLE
Open github discussion for users to share their own rules

### ISSUE THREAD

**Issue by proItheus** [gyng/save-in#195]
As asked in this issue #191 ,I also think it's great to add more use examples. But It may be more effective to let it happen by utilizing the power of community than using wiki, which still needs manual review from the developer. I think github discussion is a good place for that, and have seen several projects utilizing it, like [this](https://github.com/SilentVoid13/Templater/discussions).

**Comment by gyng** [comment]
Thanks for the suggestion. I've opened up discussions.
