### ISSUE TITLE
Save to certain folders based on site

### ISSUE THREAD

**Issue by Stetoskop** [gyng/save-in#2]
Hey there, I've got this one problem that would help me a ton if it was addressed.
When right-clicking links of torrent downloads, I only get a torrent.php file, I am aware that this is how it's supposed to work, at least on the sites/links I use that don't link directly to a .torrent file. Is there a solution for this?
Another suggestion I've got is to add an option to save to certain folders based on site that it's downloaded from. For example, if I download an image from www.examplewebsite.com and choose to save it to DOWNLOAD-DIRECTORY/images/examplewebsite.

**Comment by yupi2** [comment]
The file-name is in the response header [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) but I don't know if that can be accessed. Probably needs to use XHR

**Comment by gyng** [comment]
There are two separate issues here. I'll track the filename/Content-Disposition issue in #3, and leave this issue for the feature request.

**Comment by gyng** [comment]
I've released 1.1.2 with `:sourcedomain:`, `:pagedomain:`, `:pageurl:`, `:date:`. Please re-open if it doesn't work as expected.
