### ISSUE TITLE
Firefox detected as chrome

### ISSUE THREAD

**Issue by nico202** [gyng/save-in#214]
I'm using firefox 123.0.1 on ubuntu (snap). The settings appear like this:
![image](https://github.com/gyng/save-in/assets/8214542/72cf0426-8dfa-4441-ab2e-6ce7543fd6d4)
options with "firefox" are disabled, options with "Chrome" label are enabled.

I see that the chrome detector script checks for `typeof browser` https://github.com/gyng/save-in/blob/8960e020772137d8399876e0740395cd2e166ff0/src/chrome-detector.js#L28 which on the console returns "undefined"
![image](https://github.com/gyng/save-in/assets/8214542/19a67b3a-ff8f-4401-9f67-c375356816a7)

**Comment by gyng** [comment]
Thanks for the report. 3.73 has been submitted to the Firefox AMO which should fix this. The options page was disabling controls before before browser detection was completed.

**Comment by nico202** [comment]
Thanks! Closing as it seems to be fixed :)
Now my main problem is #212
