### ISSUE TITLE
Chrome version saving to /Downloads/undefined

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#23]
[Edited out, Posted in error to the wrong repo]

**Comment by DanaMW** [comment]
Forgive me I mean uget was toggled ON. The more I think about it , this might not be your issue?? It is doing it toggled on or off.  Also on firefox on some files I get an '_' at the start and end of file names once sent to uget. _filename.ext_ and also they are tagged with __D__Downloads__filename.ext  sometimes. It goes to the normal dialog (and looks normal  there) then fails to download (popup notification, good) and is passed to uget where it is tagged like above. I use Grab Any Media so once again I am not blaming your extension but maybe a combo of the two  or something. I can live with it because it works but i figured I better post it as someone smarter than I might have an idea.

**Comment by DanaMW** [comment]
Lastly can uget support blob? 
tampermonkey-backup-chrome-2017-11-17T06-06-08.494Z.zip
blob:chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/a4abde9a-5983-4a23-962

**Comment by gyng** [comment]
I don't know anything about uget integration. You might want to check the extensions' consoles for any hints as to what's wrong. Does this only happen with uget integration?

**Comment by DanaMW** [comment]
Oh man I have been looking for this i posted it in the wrong place I will move it and get rod of it I am truly
 sorry.

**Comment by DanaMW** [comment]
Once again Very sorry, to many browsers open.
