### ISSUE TITLE
Feature Request: more date and time related variables

### ISSUE THREAD

**Issue by anno1973** [gyng/save-in#24]
It would be very convenient if there would be also the following variables:
:year: (= 2017),
:day:  (= 01..31),
:month: (= 01..12),
:hour: (= 00..23), and
:minute: (= 00..59).

**Comment by gyng** [comment]
I'll put this in the next update.

**Comment by gyng** [comment]
Landed in 1.5.0. Please reopen if it doesn't work as expected.
