### ISSUE TITLE
Not working on Firefox Extended Support Release

### ISSUE THREAD

**Issue by AikoShidou** [gyng/save-in#27]
I had to go back from Firefox Quantum because several bugs with other addons and video playback occured. On Quantum Save-in worked just as intended, but on FES is doesn't show up in the dropdown menu at all, although it isn't grayed out in the addon list. According to FES it is working just fine. Which it isn't.

I know there isn't much gain in fixing a bug concerning such a limited release of Firefox, but maybe it is very easy to correct? Or maybe the error is on me and you can tell me what I am doing wrong?

Greetings.

**Comment by gyng** [comment]
1.5.1 should(?) fix this, please reopen if it doesn't work as expected.
