### ISSUE TITLE
Filename not saved properly

### ISSUE THREAD

**Issue by irvinm** [gyng/save-in#3]
- Open:  https://drscdn.500px.org/photo/230363917/m%3D2048_k%3D1/v2?webp=true&sig=d36ac58bd0bf2cfa317dd07981da6f997bed3ceea6f2ab077a7b721b88cdb585

- "Save in" -> Folder

- Notice that the filename is just saved as "v2" which is obviously part of the final part of the URL.  File is saved properly and can be handled by adding ".jpg" but name is sub-optimal obviously.

- Using Firefox default right-click option "Save Image As" saves as "stock-photo-230363917.jpg"

- Using old add-on "Save File To" (Pre-WebExtension) also saves as "stock-photo-230363917.jpg"

**Comment by gyng** [comment]
As mentioned in @yupi2's comment https://github.com/gyng/save-in/issues/2#issuecomment-333700570, the filename (in this case) comes from the Content-Disposition header: `filename=stock-photo-230363917.jpg`.

An empty filename parameter is not used so the directory where the file is saved in can be chosen. The path/filename for saved files is passed in to [`download.download()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download) at https://github.com/gyng/save-in/blob/fc23d743097d5c588c03919b39d89b912ab30c17/src/index.js#L53

Right now the filename is extracted from the URL, but it might be possible to hook into [webRequest.onHeadersReceived](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onHeadersReceived) and check for Content-Disposition headers. I'll take a quick look (tomorrow?) and see if anything can be done.

**Comment by yupi2** [comment]
I was looking into using `XMLHttpRequest` or `fetch`[1](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) [2](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to send a `HEAD` request to grab the content-disposition then download with that filename but I don't know how to access the content-disposition from the response headers of either.
Chrome also has [`chrome.downloads.onDeterminingFilename.addListener`](https://developer.chrome.com/extensions/downloads#event-onDeterminingFilename) which might help but I haven't tried it yet.

**Comment by gyng** [comment]
Used `fetch`. Will release https://github.com/gyng/save-in/releases/tag/v1.1.0-rc.0 soon if nothing goes wrong.

**Comment by yupi2** [comment]
There seem to be edge cases for content-disposition handling: the current regex doesn't seem to handle quoting characters correctly (`"` and probably `'` too) which can cause the closing quote to be left at the end of the filename eventually being replaced with an underscore.
Also UTF-8 encoded filenames (with characters outside of the ASCII range) cause problems.
It appears to put something like `filename = decodeURIComponent(escape(filename));` in the download function which fixes up the UTF-8 problems.

Here's an example link with the filename being `(画集・設定資料集) シャイニング・フォース イクサ ビジュアル設定資料.torrent`
https://nyaa.pantsu.cat/download/D6C6CD7025E20CCCFE5ED89F87E52BC4F7D43BD8

**Comment by gyng** [comment]
Thanks for testing!

I've made another quick [RC](https://github.com/gyng/save-in/releases/tag/v1.1.0-rc.2) with

* utf8 Content-Disposition headers
* a different Content-Disposition filename regex

I'll do more testing over the next few days.

**Comment by yupi2** [comment]
Awesome, thanks.

**Comment by gyng** [comment]
I've released 1.1.2 that should fix this, but I don't know what other bugs will surface. Please re-open if that doesn't seem to fix this.
