### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#34]
Wow your really hitting a home run with all the changes thank you for this. Doing some great work.
 So It figures I would run into a tiny problem. I entered some erroneous information in the regex box. I switched the asterisk and the period, well at first it was slow to bring up the menu and then it failed to bring up the save-in sub menu.  I am really just pointing out that any small error kills the whole extensions use. I was trying to just plant in your mind we could use some error handling maybe?  More of a feature request. 
Thank you again.

**Comment by gyng** [comment]
Thanks for the report – 1.6.0 should fix this.

**Comment by DanaMW** [comment]
Thanks once again.
