### ISSUE TITLE
Using Symlinks do not behave correctly in Windows 10

### ISSUE THREAD

**Issue by Tamalero** [gyng/save-in#37]
**Symlink behaviour is skewed with this program and saves in a nested folder instead of target folder.**

**Example:**

c:\download is the default download filter
d:\datos is my image folder
d:\datos as 3 directories d:\datos\porn d:\datos\cute d:\datos\fanart
Create a c:\download symlink using MKLINK tool named "datos"

Windows 10's explorer correctly goes from c:\download\datos to d:\datos ( real address goes as c:\download\datos\ and all content  of d:\datos is visible in windows 10 in this address)

Now the strange phenomena.

If I set the program to "save" to "datos\cute."
The file is successfully saved, but in a nested repeated directory d:\datos\datos\cute  (the addon creates the new directory structure)

saving as "\datos\cute" yields a "error, file moved or is missing".

using msdos and any other tool to copy to the symlink correctly works.

Am I doing something wrong?

**Comment by gyng** [comment]
What was the command you ran mklink with, and what are your settings?

**Comment by Tamalero** [comment]
Command for Directory, tried both Junction and normal symlink:

mklink /D DATOS F:/DATOS
Inside download directory F:\DOWNLOAD  (configured as default download dir)

Inside the ADDON:  DATOS\DIR1
Result:  Creates F:\DATOS\DATOS\DIR1 instead of saving F:\DATOS\DIR1

**Comment by gyng** [comment]
I can't seem to replicate this, do you have a filename rewrite rule that is adding DATOS?

**Comment by Tamalero** [comment]
No, that field is empty

**Comment by gyng** [comment]
I still can't replicate this. This is a very weird bug.

* Does resetting settings to defaults (copy your settings somewhere first) fix it?
* Do other directories/symlinks have the same problem?
* Is it a networked drive?
* What language/region is Windows using?
* Is it possible to paste your settings here?

You can wait and see if the next major version (coming soon!) fixes this, or, if you're interested enough, [dig through](https://github.com/gyng/save-in/wiki/Getting-detailed-error-logs) the debug console (with/without debug logging).

I will probably spend some time trying to replicate this after I get the next release out, since it seems interesting.

**Comment by Tamalero** [comment]
Did Reset, tried again remaking the mklink command, DATOS link directory appeareed in f:\download, towards target F:\DATOS, still creates another directory  ( f:\datos\datos\ )
I tried different combinations, they either not work or do the same behaviour.
Is not a networked file, its a partitioned hard disk drive (single HDD, divided into F:/ and E:/
I'm located in Mexico but my windows is set to English, Keyb Layout is also US.


**My Settings:**

Menu Items:

DATOS\By-Date\2017\2017-11
---
Datoslink\By-Date\2017\Fanart\TMNT
Datoslink\By-Date\2017\Fanart\TMNT\TMNT-Comics
---
Datoslink\By-Date\2017\Fanart
---
Datoslink\Comics - By Artist - By Group\Cosplay
Datoslink\-=Anime=-\Animee
Datoslink\-=Photo=-
---
\Image Downloads\cutestuff  (note all the attempts I tried to make it work. The appworks fine if I set the default download to F:/ and then link to DATOS\BY-DATE\   but I do not want all my files to be downloaded to F:/ !!)
I think this has to be the most silly and frustrating change by Firefox.

Rewrite Filenames:
"optional" (aka no changes from default)

Enable save of links : Check
Open a save file dialog if filename has no extension: Check.

Show notification on download  CHECK
Show notification on failed  CHECK

Save shortcuts set to HTML
no other option is enabled.

**Comment by gyng** [comment]
I don't know if this is the problem but I managed to replicate something similar.

If `Content-Disposition` contains a `/`, the extension will treat it as an additional directory. So, if the download returns a `Content-Disposition` of `datos/somefile`, the extension adds an additional directory into it.

If it's not sensitive, do you have a link to the file you are trying to download? Or, can you check the `Content-Disposition` header of the file?

**Comment by Tamalero** [comment]
How do I know how to check the "content disposition" thing for each image?

**Comment by gyng** [comment]
Can you see if this is still happening under 2.0.0?

**Comment by Tamalero** [comment]
Hello!

So far it seems to be working. I will be testing and get back to you.

Thank you!
