### ISSUE TITLE
Feature request (path with rewrite rule; clipboard; source URL; capture group; invalid characters)

### ISSUE THREAD

**Issue by Gnustier** [gyng/save-in#39]
Feature request (path with rewrite rule; clipboard; source URL; capture group; invalid characters)

Can you please, 

add new feature : 
　　filename rewrite rule can be used together with path, 
　　each path can use multiple rewrite rules and get different filename.
　　example of path items : 
　　　　`wallpapers/<rewrite-rule-1>`
　　　　`wallpapers/<rewrite-rule-2>`
　　　　`cats/<rewrite-rule-1>`
　　　　`cats/<rewrite-rule-2>`

add new variables : 
　　- clipboard.  works on everywhere
　　- source URL.  works on everywhere

change existing variable : 
　　make capture group works on everywhere

add new feature : 
　　replace the invalid characters in the filename with user specified characters

**Comment by gyng** [comment]
Bunch of requests here:

* The syntax/UI for multiple rewrite rules will need some thinking. Maybe the upcoming filename rewrite upgrade will work well enough.
* Not sure about the utility of clipboard. What/how do you use it?
* `srcurl` is coming soon
* Some form of this is coming soon with filename rewrites upgrades
* Invalid characters: easy and reasonable request, I'll do it

**Comment by Gnustier** [comment]
I would use clipboard on these situations : 
　　- filename has no relation with file content. 
　　- multiple files has similar content subject, 
　　　and filenames has no relation with content subject. 
　　　example : 
　　　　`sunset beach. 1234.jpg`
　　　　`brown cat. 7890.jpg`
　　　　`2018 Honda new car. abcd.jpg`
　　　　`2018 Honda new car. wxyz.jpg`

**Comment by gyng** [comment]
* Filename rewrite can be used together with path now
* Instead of `:clipboard:` which is annoying to implement I've added `:selectiontext:` as a compromise instead.
* `:srcurl:` in 2.0
* Capture groups should be more flexible now with the new syntax
* Invalid characters is in 2.0

I've left out the per-item rule. No intent to implement that right now. Please reopen if the 2.0 additions don't work as expected.
