### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#4]
Nice easy setup, thanks for adding it to firefox. My question is would you consider adding a notification succeed/failed and location for some indication that it completed as planned?
And it seems that the check box to enable saving links is always checked even if i uncheck and save.

**Comment by gyng** [comment]
Not at the moment, but it can be something to consider for future releases. I feel the giant blue arrow over the downloads button in Firefox generally works fine, though I recall discovering a handful of failed downloads after the fact.

The checkbox not saving is a display bug, thanks for reporting it! I'll get on fixing it.

**Comment by DanaMW** [comment]
Currently I end up with a large number of files that have to be renamed as they save as say blahblah.jpg_Large or  weird names like that.

**Comment by gyng** [comment]
Ah, yes, it will be useful in for that. I wouldn't mind having this in as an option.

Would an option to strip extra characters after a `.jpg` or a `.png` be also useful in this case? Twitter images always have this problem.

**Comment by DanaMW** [comment]
That was my thought exactly, maybe even  better make it user defined like a variable  subset where they can add [sometext] and can either strip it off  or rename  it to  cover many more likely problems.. I  dont know just a thought.

**Comment by DanaMW** [comment]
then they can have more than one rule to cover a number of things they might run into.

**Comment by gyng** [comment]
Will need to figure out a nice way of implementing this.

Meanwhile I've added an option to open the file save dialog when saving as a stopgap.

**Comment by DanaMW** [comment]
Thank you. It is nice not having to hit the extra keys but better than having to  go back and fix a bunch.
I have  a question ... can these web extensions access the browser cache ? for saving the file from there. I was thinking it would be a lot faster and also prevent the double get requests to the web sites ... lol just another thought.

**Comment by gyng** [comment]
It should be using the browser cache right now, even for Firefox. The extra HEAD request is only for not-Chrome, and does not make a full request. Firefox will have to implement https://developer.chrome.com/extensions/downloads#event-onDeterminingFilename before the extra HEAD request (and a whole bunch of filename handling code) can be killed.

**Comment by DanaMW** [comment]
ok very good.  I just started looking through your code a couple hours ago,  i forked it, over to me i could work on taking it all in so i would not have to ask all those stupid questions. Hope that is all cool with you.

**Comment by irvinm** [comment]
It is situations like this that I will really miss "Download Manager (S3)" ([https://addons.mozilla.org/en-US/firefox/addon/s3download-statusbar](url)) as it used the status bar to simply show what was downloaded, was it successful, and what was the final filename used.

As there is no status bar in FF57+ I am hoping there is some other way to "show" this information as a notification other that just the download arrow animation.

For me, I always want to check if I had already downloaded that file and that the extension was properly captured.  It was easy to visible inspect the information [filename(2).ext] and configured it clear itself after "x" number of seconds.  I can't currently do either without clicking on the download arrow after each download.  I could even delete the local file if it was a duplicate right from the status bar.

**Comment by DanaMW** [comment]
Saw your push.. thanks man :)

**Comment by gyng** [comment]
Basic notifications released with v1.3.

**Comment by DanaMW** [comment]
Yes thank  you for you work once  again .. This extension works great for me.

**Comment by DanaMW** [comment]
Hey sorry, I was wondering if you made the timeout on notifications configurable? They stay open  a good while on my machines. On some sites I can fill the side of the screen with them.

**Comment by gyng** [comment]
It's using the browser/OS default, but shouldn't be too hard to add in. I'll do it in a future release.

**Comment by irvinm** [comment]
Maybe one other suggestion:  Can we make it configurable as to left or right notifications?  (Using TreeStyleTab, vertical tabs are typically placed along the left and the notification covers them up.)

**Comment by irvinm** [comment]
Nevermind.  I did some research into this and the notifications are related to the position of the "Windows Task Bar" and in this case I also have it vertically on the left and therefore the notifications show up in the lower left for me and it doesn't appear to be any location options related to notifications.create() or notifications.NotificationOptions.

**Comment by gyng** [comment]
Released 1.3.1 with maximum notification duration.

Yeah, there's no setting for notification position in the API since it's using OS notifications. I'm hesitant of rolling my own as that's more code that I would like. Hopefully a shorter-lasting notification will clear up the screen.

Closing this issue, please re-open if it's not solved.

**Comment by DanaMW** [comment]
Thank  you again.
