### ISSUE TITLE
"Save by page title seems to have a bug"

### ISSUE THREAD

**Issue by CorakTM** [gyng/save-in#41]
This extension is a godsend after Firefox broke my old one, and the additions of new naming options has helped a lot. However, I've run into a slightly annoying bug where the :pagetitle: only uses the title of the page when the tab was first opened, saving as the same title when a page is changed. I figured I'd report it to you in case you weren't aware of ift, since I wasn't able to find it mentioned by anyone else in the time I looked.

**Comment by gyng** [comment]
Thanks for the report, this should be fixed in 2.0.0.
