### ISSUE TITLE
Only the first separator from the list of menu items is shown

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#44]
Save In v2.0.1, on Nightly.

STR: have multiple `---` entries in the item list.
AR: only the first `---` shows up as a separator; rest are apparently ignored.

Seems to be a recent regression.

**Comment by gyng** [comment]
Caused by a pile of hacks upon hacks (not allowing duplicate paths).

Should have another hack to fix this in 2.0.2.
