### ISSUE TITLE
[Feature request] Possible to show size of download in the successful download notification?

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#48]
Unsure if possible with webextensions.

The reason I ask is because some websites redirect your request, resulting in a tiny html file getting saved instead. E.g. happens often with Imgur because it redirects mp4 to gifv.

**Comment by gyng** [comment]
Huh, I thought I had this implemented. I'll put it in the next release.

**Comment by gyng** [comment]
Landed in 2.2.0. Thanks for the issue!
