### ISSUE TITLE
Feature Request: Different renaming rules for different save paths

### ISSUE THREAD

**Issue by KatakiriKasai** [gyng/save-in#49]
Hello. Could you add an option to set an individual rule for each path?
For example
1. Images\folder1\:filename:.:fileext: - saves file to Images\folder1 with its original name
2. Images\folder1\ - the same as above
3. Images\folder1\:unixdate:.:fileext: - saves file to Images\folder1 and renames it
4. Images\folder2 - saves file to Images\folder2 with its original name

**Comment by gyng** [comment]
I've added `comment:` and `menuindex:` matchers in 2.3.0. You can now add a comment to a path with `//`. I haven't tested it out much, so report any bugs you find!

Eg.
```
Images/folder1/:filename:.:fileext:
Images/folder1/:filename:.:fileext: // rename
```

And then in the rules

```
comment: rename
into: :unixdate:.:fileext:
```

or

```
menunidex: 1
into: :unixdate:.:fileext:
```
