### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by hiasl360** [gyng/save-in#5]
Is it possible to add the date and time to the name of the downloaded file?
I'd like  to have it that way: YYYYMMDD-HHMMSS-original filename.
e.g.: 20171019-203530-test.jpg

**Comment by gyng** [comment]
Yes, this is something I've been wanting to implement. The main blockers here are the UI/UX, and deciding what features to allow for filename rewrites.

**Comment by gyng** [comment]
1.4 doesn't have the exact same date format, but does it work?

```
.*
:isodate:-:filename:
```

**Comment by hiasl360** [comment]
Yes it works

**Comment by gyng** [comment]
Thanks for catching that. Dates are now padded with a 0.
