### ISSUE TITLE
Ascii Character 160 causes issues in certain paths

### ISSUE THREAD

**Issue by tigre7575** [gyng/save-in#53]
The Ascii character 160 (non breaking space) is causing an issue for one of my paths. I have my download folder set as E:\ and I'm trying to add E:\ \something as a path but it doesn't work.

test\[nbsp]\test // this works
test[nbsp]test // this also works
[nbsp]\something // this fails without saving a file
test\[nbsp] // fails but saves a file to E:\test

It seems having the non breaking space as the leading or trailing character of a path does not work.

**Comment by gyng** [comment]
Browsers intentionally treat whitespace as invalid directories, I can't do anything about this.

#16

https://dxr.mozilla.org/mozilla-central/rev/d4753dc14b2ab9c42123b6d60a68106df40f45cd/toolkit/components/jsdownloads/src/DownloadPaths.jsm#70
