### ISSUE TITLE
[Request] Optionally, always show the 'Save as' dialog box when a modifier key was used while clicking a context menu item / folder path

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#55]
I believe this [is possible](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/OnClickData) using the `modifiers` property; please ignore if isn't.

Rationale: I keep ` Open a save file dialog when saving` unchecked because it works well enough and it is quicker not having to go through the dialog, but sometimes:

* I would like to rename the file, maybe because I expect a duplicate filename
* I would like to save to a location that (a) isn't added to SaveIn's directory list, but (b) is still closer to reach from one of the locations that is already added, compared to using the browser's save feature which will launch the Save As dialog at the Downloads folder.

The legacy [Save Image in Folder](https://addons.mozilla.org/en-US/firefox/addon/save-image-in-folder/) used to have this feature where while clicking a folder path context menu item would save without showing the Save As dialog, shift+clicking the folder path would launch the Save As dialog at that folder:
![saveimageinfolder_screenshot1](https://user-images.githubusercontent.com/8336638/35306336-1987889c-00c3-11e8-82b9-48d32ed6580d.png)
Would be great if Save In could do the same.

**Comment by gyng** [comment]
Thanks for the well-written request! Seems like a good and easy enough thing to add. I'll look into it once I get some fee time.

>I expect a duplicate filename

I'm still waiting on Firefox to implement [downloads.FilenameConflictAction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/FilenameConflictAction)

https://bugzilla.mozilla.org/show_bug.cgi?id=1425515

**Comment by gyng** [comment]
Added in v2.4.0. Please reopen if it doesn't work as expected.
