### ISSUE TITLE
Save to %temp% directory feature request

### ISSUE THREAD

**Issue by 13regent** [gyng/save-in#58]
I download a lot of files that I like to run immediately, but don't care about the saved files. I find it annoying to then go and delete the files. It would be nice to have a built in feature to have the option to download to the %temp% folder.  I use Ccleaner,  and it deletes files from the temp folder older than 24 hours.

**Comment by gyng** [comment]
WebExtensions do not allow saving into arbitrary directories. To get what you want, you will have to create a symlink to your `%temp%` inside the default downloads directory, and then use that symlink instead.
