### ISSUE TITLE
File Extension

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#6]
I was wondering if you could make is so if the file did not have an image extension it would pop up the save file dialog? maybe that would be easier than parsing and changing the  extension of the file?

**Comment by DanaMW** [comment]
The only other thing that came to mind was allowing variables like your system ones except for file extension, either defined like you have or maybe user defined. They can be either find and replace format or simply overwriting the files current. Just a thought.

**Comment by gyng** [comment]
Tracked in #5

**Comment by gyng** [comment]
I noticed the request for the toggle, and added it in 1.4. The extension detection is primitive, but hopefully it works well enough.
