### ISSUE TITLE
Image enlarge

### ISSUE THREAD

**Issue by Sjkomy** [gyng/save-in#60]
I do encounter an issue although it is not addon's problem, many images that i download are large, so clicking on them using click to save makes them pop out. Is there any way to turn this function off in firefox ...

**Comment by gyng** [comment]
I'll investigate adding it as an option when I get the time.

**Comment by gyng** [comment]
I'm assuming this is for Firefox's built-in image viewer?

Propagation for the click event on the image is already being prevented, but the image width/height is still being set. Will have to dig further.

**Comment by Sjkomy** [comment]
Thnk you for your efforts. Most of the time it works as intended, but sometimes it doesn't. (For example just after page reloads) I do understand it has to do with site's scripts so joyreactor.com or joyreactor.cc.

**Comment by FatOrangutan** [comment]
@gyng: Maybe change the shortcut for click-to-save to work with right click? Like alt + rclick by default?

**Comment by gyng** [comment]
@FatOrangutan Seems like a decent-enough workaround. I'll see if I can improve the shortcut option or make left/right click an option.

**Comment by gyng** [comment]
There's now an option to pick which mouse button to use with the combo in 2.6.0 that I think should solve this issue. Please reopen if it doesn't seem to work.
