### ISSUE TITLE
Context Menu display name alias

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#64]
I was wondering how you might feel about a request  for an alias for folder names on the context menu? If the path is long to a given folder it might be useful to be able to have it display as a user configured alias.
using  setup similar to others you use it could be added to the menu maybe
.
Pictures:Pictures:
Pictures/2018/Family/Child:ChildName:

Or on the next line maybe? Just a thought to keep my menu reasonable.. Thank you friend.

**Comment by gyng** [comment]
I'll need to think of a nice way to do it without overloading the syntax.

**Comment by gyng** [comment]
I've added aliases to v3.1.0, to use them add `(alias: display name)` to the line's comments.

```
cats // (alias: actually dogs)
```

**Comment by DanaMW** [comment]
Thank you for your work great update there @gyng

**Comment by gyng** [comment]
I thought I had fixed that in dev, updated with v3.1.1.

**Comment by DanaMW** [comment]
Thank you and installed and working
