### ISSUE TITLE
Saving to default downloads directory

### ISSUE THREAD

**Issue by MindlessCirno** [gyng/save-in#7]
For some reason saving directly to downloads directory (witch "." path) now don't work

**Comment by gyng** [comment]
Do you have more details? I cannot replicate this.

**Comment by DanaMW** [comment]
Thanks for your work and changes!

**Comment by MindlessCirno** [comment]
Here what I done: restarted firefox, opened debug console for "Save in" and there is errors already:

```
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.  components.manifest:177
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  background.js:5:173
```

Then I tried to save this picture [](https://i.imgur.com/u554hJL.jpg) to downloads directory `C:\Users\lambda\Downloads\` and this error appeared:

`Error: filename must not contain illegal characters`

Tried this with 1.4.1 version

**Comment by gyng** [comment]
Somehow, nightly stopped accepting filenames that start with `./` such as `./some_filename` as valid. The initial error messages are not from save in.

Please try 1.4.2 and see if it fixes the problem.

**Comment by MindlessCirno** [comment]
It works now. Thank you!
