### ISSUE TITLE
Append the saved text...

### ISSUE THREAD

**Issue by Lejomoz** [gyng/save-in#71]
Hello,
If there are no Quantum limitations, can we have an option to append the consecutive saved text from the same page instead of saving it to a new file?

**Comment by gyng** [comment]
Thanks for the request! This is not possible without much effort as extensions have no access to the filesystem. You can try using an advanced clipboard program/manager and see if that helps.

**Comment by Lejomoz** [comment]
Thank you for your response and suggestions. And thanks for the great add-on of course. :)
