### ISSUE TITLE
adding Dutch locale messages

### ISSUE THREAD

**Issue by 80486dx** [gyng/save-in#72]
Would it be possible to include the Dutch language (nl) for the messages.
[_locales.zip](https://github.com/gyng/save-in/files/2079587/_locales.zip)

**Comment by 80486dx** [comment]
I'm with you, incomplete localisations is bad. I am a native Dutch speaker. I'll add the missing translations as soon as the hooks are found.

**Comment by gyng** [comment]
@80486dx I've dumped a whole bunch of localisation hooks in 2.7.0, but please don't feel pressured to fill those out. I've also included (but left disabled) the nl localisation file you included in the first post in the extension. Thanks for your contribution!

**Comment by 80486dx** [comment]
[_locales.zip](https://github.com/gyng/save-in/files/2201118/_locales.zip)
Thanks a lot for including the nl locatisation file. I have filled out the Dutch localisation hooks for 2.7.0.

PS As a workaround for not writing outside the Firefox download-folder, I have set the Firefox default Download dir to the root of the user home directory.

**Comment by gyng** [comment]
I've had trouble testing it in Firefox because my local setup isn't configured for nl, but it seems to work in Chrome. Since it seems to cover most places I've gone ahead enabled this in 3.1.0.

**Comment by DanaMW** [comment]
Thank you for your work great update  there @gyng
