### ISSUE TITLE
Save In... Grabs Image when I would prefer Link

### ISSUE THREAD

**Issue by shubniguroth** [gyng/save-in#75]
Is there a way to get Save In... To always prefer the link instead of the media when I'm right clicking an image that contains a link?

Thanks,
Shub

**Comment by gyng** [comment]
I've added an option to "Prefer links over sources" in 2.7.0. Please try it out as I'll be closing this issue soon if no bugs are found.

**Comment by gyng** [comment]
Marking this as done, please reopen or create an issue if problems are found.
