### ISSUE TITLE
No notifications when using "ALT+Click" shortcut

### ISSUE THREAD

**Issue by GallaherMike** [gyng/save-in#78]
In Chrome 67.0.3396.99 (Official Build) (64-bit) when I use the "ALT+Click" shortcut to save to the last used folder there is no notification. I have tried changing all the notification settings. 

The image does save correctly, but there is no notification that is did so.

**Comment by gyng** [comment]
Thanks for the bug report. 2.7.3 should fix this.

**Comment by GallaherMike** [comment]
Confirmed this is now working.

Thanks.
