### ISSUE TITLE
Context menu accesskeys no longer work. 

### ISSUE THREAD

**Issue by GallaherMike** [gyng/save-in#79]
This might be a chrome issue, but the access keys in chrome no longer work. 
i.e. context menu > a does nothing

Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by gyng** [comment]
Thanks for the report and sorry for the breakage. There was a Chrome polyfill change recently, I'll take a look.

**Comment by gyng** [comment]
Thanks for the bug report. 2.7.3 should fix this.

**Comment by GallaherMike** [comment]
Confirmed working again.
