### ISSUE TITLE
'Export Settings' captures the state of settings when the options page was opened, missing changes made since then

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#83]
Save In v3.1.0, Firefox Nightly

STR:
1. Open Save In's settings, either at about:addons or the `moz-extension://[...]/src/options/options.html` url
2. Make some changes. Wait for the green tick to show up to ensure the change was registered.
3. Click `Export Settings`

AR: changes made at step2 aren't included in the export.

**Comment by gyng** [comment]
Hah, I thought nobody would notice. Fixed in 3.1.2.

**Comment by FatOrangutan** [comment]
Thanks for the speedy fix. Seems to be working. Closing the issue.
