### ISSUE TITLE
The check mark for 'saved successfully' in the options page can get hidden behind scrollbar

### ISSUE THREAD

**Issue by FatOrangutan** [gyng/save-in#84]
`#paths` and `#filenamePatterns` typically have scrollbars for me and making any changes in these text boxes shows up the green check mark partially hidden by the scrollbar.

**Comment by gyng** [comment]
Thanks for the report, looks like this happens for not Mac OS since the scrollbars aren't hidden. Updated the styling in 3.1.2.
