### ISSUE TITLE
Wanted to say....

### ISSUE THREAD

**Issue by DanaMW** [gyng/save-in#85]
Thank you. Been (over) testing this now since the last updates  and it has gotten a lot more useful and refined because of them. Thanks for all the work and for this extension. It is my most used extension.that doesn't style pages. Great job here. It should be way more popular than it is. Not another one as good that I have seen. I'll find a way to promote it lol. Really fine job thanks you.

**Comment by gyng** [comment]
Thank you for the kind words!
