### ISSUE TITLE
Separate "save from tab strip" command.

### ISSUE THREAD

**Issue by ZzzZombi** [gyng/save-in#88]
Hi there. Is it possible to put the saving from tab strip (for firefox, of course) commands to the default right click context menu? Or any other way to reach that menu apart from clicking on a tab?

I'm asking because I hide the default tab strip on Firefox and use a vertical tab bar addon that only emulates the default tab context menus and naturally save-in's tab commands are not visible there.

It's not a huge deal, obviously. Just asking to get an idea.

**Comment by DanaMW** [comment]
Hey Ng I wanted to chime in on this before you thought to long to mention that maybe it would be easier to add another class to the menus since we already have access to them and might allow 
``[:]``Entering  extension commands. (or more) Was just a thought. :)

**Comment by gyng** [comment]
@ZzzZombi I don't think it's quite possible since it's done through the web extensions API directly. It might be possible to put some of the more useful commands inside the right-click submenu as well, but I'll have to investigate that.

@DanaMW I don't understand what you're suggesting, can you clarify?

**Comment by gyng** [comment]
@ZzzZombi I think this is implemented in Firefox 64, and doesn't need any change in save-in. It seems to work fine in Tree Style Tab 2.6.8 with FF64.

* https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm
* https://blog.mozilla.org/addons/2018/11/08/extensions-in-firefox-64/
