### ISSUE TITLE
SaveIn creates new directory instead of defined one.

### ISSUE THREAD

**Issue by ZzzZombi** [gyng/save-in#9]
Just today, on Nightly, extension started to create a new folder with a "_" at the beginning instead of saving to my defined folder.

For example I have a symlink called "Pics" in this folder "C:\Users\username\Downloads\-" and in extension config the path is set to "-/Pics". When I save a picture to that folder it creates a folder called "-_Pics" in the default Downloads folder instead of saving to "-/Pics" and saves it there.

I don't know if it might be a bug in latest Nightly.

**Comment by gyng** [comment]
Sorry, this was introduced in 1.4.

It happens when you have nested directories. I'll get a new release done soon.

**Comment by gyng** [comment]
Please try 1.4.1, and see if this is still happening.

**Comment by ZzzZombi** [comment]
Yep, working great now. Thank you for your work.
