### ISSUE TITLE
Update to Firefox 63 extension APIs

### ISSUE THREAD

**Issue by gyng** [gyng/save-in#91]
Also consider holding off until next Firefox ESR, Chrome support

* Multi-tab select (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs)
  - Highlight tabs downloaded
* Enable access keys for Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1320462)
* Investigate alternative modifier keys for shortcuts (https://bugzilla.mozilla.org/show_bug.cgi?id=1364784)
* `menus.getTargetElement` might be able to allow us to grab information about an element via content script (element title and more)

**Comment by almet** [comment]
Yes please!

**Comment by gyng** [comment]
Multi-tab support, access keys for FF >= 63 enabled. Modifier keys do not seem to need any changes, and `menus.getTargetElement` is tracked by #65.
