### ISSUE TITLE
Chrome: No separator in the context menu :(

### ISSUE THREAD

**Issue by Sopor-** [gyng/save-in#95]
In the variable list i can read: `---    Creates a separator in the context menu` so I have added `---` to the context menu, but i don't get any separator. Do i need to do something more than adding `---`?

It seems to work in Firefox but not Chrome.

**Comment by gyng** [comment]
I'll take a look when I can, I'm a bit swamped right now.

**Comment by gyng** [comment]
This seems to be a bug in Chrome, fixed in Chrome 72

https://bugs.chromium.org/p/chromium/issues/detail?id=904220

**Comment by gyng** [comment]
This was fixed by Chrome 72, which is now stable.
