### ISSUE TITLE
Chrome: will not save to default folder after saving to another folder with Save In

### ISSUE THREAD

**Issue by Sopor** [gyng/save-in#96]
After using `Save In` and saving to one of the non default folders (non default folder in Chrome)  it seems that when i save using Chrome's built in save, it will not save to the default folder. Instead it will use the last folder i have used in `Save In`.

**Comment by DanaMW** [comment]
i wonder if that can be related to the setting "Show last menu item"

**Comment by Sopor-** [comment]
To change the default Chrome path i need to use Save In again or else it will continue to use the last path i used in Save In. In Chrome setting under Location i can see the correct default path. Even if i press change and OK it will not work. It will continue to use the last path i used in Save In when i use Chrome `Save link as` or if i press on file extensions that will auto download without any prompt.

**Comment by DanaMW** [comment]
Thank you NG, once again , for your great work.
